import React from 'react';

const LogoAsciArt = () => {
    return (
        <code class="asciArt">
            <p>
                <span style={{ color: "#F35B42" }}>/</span><span style={{ color: "#F35B42" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F35B42" }}>/</span><span style={{ color: "#F35B42" }}>/</span><span style={{ color: "#F35B42" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F35B42" }}>/</span><span style={{ color: "#F35B42" }}>/</span><span style={{ color: "#F35B42" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F35B42" }}>/</span><span style={{ color: "#F35B42" }}>/</span><span style={{ color: "#F35B42" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F35B42" }}>/</span><span style={{ color: "#F35B42" }}>/</span><span style={{ color: "#F35B42" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F45B43" }}>/</span><span style={{ color: "#F35B42" }}>/</span>
            </p>
            <p>
                <span style={{ color: "#F35843" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F35843" }}>/</span><span style={{ color: "#F15743" }}>/</span><span style={{ color: "#F15743" }}>/</span>
            </p>
            <p>
                <span style={{ color: "#F25444" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05444" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F25444" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05444" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F25444" }}>/</span><span style={{ color: "#F05443" }}>/</span><span style={{ color: "#F05443" }}>/</span>
            </p>
            <p>
                <span style={{ color: "#F15044" }}>/</span><span style={{ color: "#EF5043" }}>/</span><span style={{ color: "#EF5043" }}>/</span><span style={{ color: "#EF4F43" }}>/</span><span style={{ color: "#EF4F43" }}>/</span><span style={{ color: "#EF5043" }}>/</span><span style={{ color: "#EF5043" }}>/</span><span style={{ color: "#EF4F43" }}>/</span><span style={{ color: "#DC493E" }}>(</span><span style={{ color: "#BA3E34" }}>#</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#6E6471" }}>(</span><span style={{ color: "#6E6471" }}>(</span><span style={{ color: "#EAE009" }}>*</span><span style={{ color: "#EAE009" }}>*</span><span style={{ color: "#07DCD4" }}>/</span><span style={{ color: "#07DCD4" }}>/</span><span style={{ color: "#18D90F" }}>#</span><span style={{ color: "#18D90F" }}>#</span><span style={{ color: "#E80BD2" }}>/</span><span style={{ color: "#E80BD2" }}>/</span><span style={{ color: "#8616B4" }}>(</span><span style={{ color: "#8616B4" }}>(</span><span style={{ color: "#6914C5" }}>(</span><span style={{ color: "#B03A36" }}>#</span><span style={{ color: "#D5473C" }}>(</span><span style={{ color: "#EE5043" }}>/</span><span style={{ color: "#EF4F43" }}>/</span><span style={{ color: "#F15044" }}>/</span><span style={{ color: "#EF5043" }}>/</span><span style={{ color: "#EF5043" }}>/</span>
            </p >
            <p>
                <span style={{ color: "#F04D45" }}>/</span><span style={{ color: "#EE4C44" }}>(</span><span style={{ color: "#EF4C44" }}>/</span><span style={{ color: "#EE4C44" }}>(</span><span style={{ color: "#EE4C44" }}>(</span><span style={{ color: "#EF4C44" }}>/</span><span style={{ color: "#EE4C44" }}>(</span><span style={{ color: "#EE4C44" }}>(</span><span style={{ color: "#CC413A" }}>(</span><span style={{ color: "#8A2C27" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#6E6471" }}>(</span><span style={{ color: "#6F6572" }}>(</span><span style={{ color: "#FDF319" }}>*</span><span style={{ color: "#FDF319" }}>*</span><span style={{ color: "#19FDF4" }}>*</span><span style={{ color: "#19FDF4" }}>*</span><span style={{ color: "#23FD19" }}>(</span><span style={{ color: "#23FD19" }}>(</span><span style={{ color: "#FD19E7" }}>*</span><span style={{ color: "#FF1AE9" }}>*</span><span style={{ color: "#9C19D0" }}>/</span><span style={{ color: "#9C19D0" }}>/</span><span style={{ color: "#7F17F1" }}>/</span><span style={{ color: "#7B2729" }}>%</span><span style={{ color: "#BE3D36" }}>#</span><span style={{ color: "#ED4B43" }}>(</span><span style={{ color: "#EE4C44" }}>(</span><span style={{ color: "#F04D45" }}>/</span><span style={{ color: "#EE4C44" }}>(</span><span style={{ color: "#EE4C44" }}>(</span>
            </p>
            <p>
                <span style={{ color: "#EF4945" }}>(</span><span style={{ color: "#EE4945" }}>(</span><span style={{ color: "#EE4945" }}>(</span><span style={{ color: "#EE4945" }}>(</span><span style={{ color: "#EE4945" }}>(</span><span style={{ color: "#EE4945" }}>(</span><span style={{ color: "#EE4945" }}>(</span><span style={{ color: "#EE4945" }}>(</span><span style={{ color: "#CA3E3B" }}>(</span><span style={{ color: "#892A28" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#6E6471" }}>(</span><span style={{ color: "#6E6471" }}>(</span><span style={{ color: "#FDF319" }}>*</span><span style={{ color: "#FDF319" }}>*</span><span style={{ color: "#19FDF4" }}>*</span><span style={{ color: "#19FDF4" }}>*</span><span style={{ color: "#23FD19" }}>(</span><span style={{ color: "#23FD19" }}>(</span><span style={{ color: "#FD19E7" }}>*</span><span style={{ color: "#FD19E7" }}>*</span><span style={{ color: "#9C19D0" }}>/</span><span style={{ color: "#9C19D0" }}>/</span><span style={{ color: "#7F17F1" }}>/</span><span style={{ color: "#7B2529" }}>%</span><span style={{ color: "#BD3A37" }}>#</span><span style={{ color: "#EC4844" }}>(</span><span style={{ color: "#EE4945" }}>(</span><span style={{ color: "#EF4945" }}>(</span><span style={{ color: "#EE4945" }}>(</span><span style={{ color: "#EE4945" }}>(</span>
            </p>
            <p>
                <span style={{ color: "#EF4646" }}>(</span><span style={{ color: "#ED4545" }}>(</span><span style={{ color: "#ED4545" }}>(</span><span style={{ color: "#ED4545" }}>(</span><span style={{ color: "#ED4545" }}>(</span><span style={{ color: "#ED4545" }}>(</span><span style={{ color: "#ED4545" }}>(</span><span style={{ color: "#ED4545" }}>(</span><span style={{ color: "#CA3B3B" }}>(</span><span style={{ color: "#892828" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#6E6471" }}>(</span><span style={{ color: "#6F6572" }}>(</span><span style={{ color: "#FDF319" }}>*</span><span style={{ color: "#FDF319" }}>*</span><span style={{ color: "#19FDF4" }}>*</span><span style={{ color: "#19FDF4" }}>*</span><span style={{ color: "#23FD19" }}>(</span><span style={{ color: "#23FD19" }}>(</span><span style={{ color: "#FD19E7" }}>*</span><span style={{ color: "#FD19E7" }}>*</span><span style={{ color: "#9C19D0" }}>/</span><span style={{ color: "#9C19D0" }}>/</span><span style={{ color: "#7F17F1" }}>/</span><span style={{ color: "#7B2329" }}>%</span><span style={{ color: "#BD3737" }}>#</span><span style={{ color: "#EB4444" }}>(</span><span style={{ color: "#ED4545" }}>(</span><span style={{ color: "#EF4646" }}>(</span><span style={{ color: "#ED4545" }}>(</span><span style={{ color: "#ED4545" }}>(</span>
            </p>
            <p>
                <span style={{ color: "#EE4246" }}>(</span><span style={{ color: "#EC4146" }}>(</span><span style={{ color: "#EC4146" }}>(</span><span style={{ color: "#EC4145" }}>(</span><span style={{ color: "#EC4145" }}>(</span><span style={{ color: "#EC4146" }}>(</span><span style={{ color: "#EC4146" }}>(</span><span style={{ color: "#EC4145" }}>(</span><span style={{ color: "#C9373B" }}>(</span><span style={{ color: "#892628" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#543A44" }}>%</span><span style={{ color: "#6E6471" }}>(</span><span style={{ color: "#6E6471" }}>(</span><span style={{ color: "#7C727F" }}>(</span><span style={{ color: "#7C727F" }}>(</span><span style={{ color: "#7C727F" }}>(</span><span style={{ color: "#7C727F" }}>(</span><span style={{ color: "#7C727F" }}>(</span><span style={{ color: "#7C727F" }}>(</span><span style={{ color: "#7C727F" }}>(</span><span style={{ color: "#7C727F" }}>(</span><span style={{ color: "#7C727F" }}>(</span><span style={{ color: "#7C727F" }}>(</span><span style={{ color: "#7C727F" }}>(</span><span style={{ color: "#7A2326" }}>%</span><span style={{ color: "#BC3438" }}>#</span><span style={{ color: "#EA4045" }}>(</span><span style={{ color: "#EC4145" }}>(</span><span style={{ color: "#EE4246" }}>(</span><span style={{ color: "#EC4146" }}>(</span><span style={{ color: "#EC4146" }}>(</span>
            </p>
            <p>
                <span style={{ color: "#ED3E47" }}>(</span><span style={{ color: "#EB3E46" }}>(</span><span style={{ color: "#EB3E46" }}>(</span><span style={{ color: "#EB3E46" }}>(</span><span style={{ color: "#ED3E47" }}>(</span><span style={{ color: "#EB3E46" }}>(</span><span style={{ color: "#EB3E46" }}>(</span><span style={{ color: "#EB3E46" }}>(</span><span style={{ color: "#D5383F" }}>(</span><span style={{ color: "#AC2D33" }}>#</span><span style={{ color: "#615563" }}>#</span><span style={{ color: "#615563" }}>#</span><span style={{ color: "#625664" }}>#</span><span style={{ color: "#615563" }}>#</span><span style={{ color: "#615563" }}>#</span><span style={{ color: "#5F444D" }}>#</span><span style={{ color: "#60454E" }}>#</span><span style={{ color: "#6B4E56" }}>#</span><span style={{ color: "#6B4E56" }}>#</span><span style={{ color: "#6B4E56" }}>#</span><span style={{ color: "#6C4F57" }}>#</span><span style={{ color: "#6B4E56" }}>#</span><span style={{ color: "#6B4E56" }}>#</span><span style={{ color: "#6B4E56" }}>#</span><span style={{ color: "#6C4F57" }}>#</span><span style={{ color: "#6B4E56" }}>#</span><span style={{ color: "#6B4E56" }}>#</span><span style={{ color: "#6B4E56" }}>#</span><span style={{ color: "#A12C31" }}>#</span><span style={{ color: "#CB353C" }}>(</span><span style={{ color: "#E93E46" }}>(</span><span style={{ color: "#EB3E46" }}>(</span><span style={{ color: "#ED3E47" }}>(</span><span style={{ color: "#EB3E46" }}>(</span><span style={{ color: "#EB3E46" }}>(</span>
            </p>
            <p>
                <span style={{ color: "#EC3B47" }}>(</span><span style={{ color: "#EB3A47" }}>(</span><span style={{ color: "#EB3A47" }}>(</span><span style={{ color: "#EB3A47" }}>(</span><span style={{ color: "#EB3A47" }}>(</span><span style={{ color: "#EB3A47" }}>(</span><span style={{ color: "#EB3A47" }}>(</span><span style={{ color: "#EA3A47" }}>(</span><span style={{ color: "#EB3A47" }}>(</span><span style={{ color: "#E53945" }}>(</span><span style={{ color: "#C5313B" }}>#</span><span style={{ color: "#A52932" }}>#</span><span style={{ color: "#7F0C10" }}>%</span><span style={{ color: "#7F0C10" }}>%</span><span style={{ color: "#7F0C10" }}>%</span><span style={{ color: "#900D11" }}>%</span><span style={{ color: "#900D11" }}>%</span><span style={{ color: "#900D11" }}>%</span><span style={{ color: "#900D11" }}>%</span><span style={{ color: "#8B0C10" }}>%</span><span style={{ color: "#8B0C10" }}>%</span><span style={{ color: "#900D11" }}>%</span><span style={{ color: "#900D11" }}>%</span><span style={{ color: "#7F0C10" }}>%</span><span style={{ color: "#7F0C10" }}>%</span><span style={{ color: "#760A0E" }}>&</span><span style={{ color: "#760A0E" }}>&</span><span style={{ color: "#BE2F39" }}>#</span><span style={{ color: "#E03744" }}>(</span><span style={{ color: "#EA3A47" }}>(</span><span style={{ color: "#EB3A47" }}>(</span><span style={{ color: "#EB3A47" }}>(</span><span style={{ color: "#EC3B47" }}>(</span><span style={{ color: "#EB3A47" }}>(</span><span style={{ color: "#EB3A47" }}>(</span>
            </p>
            <p>
                <span style={{ color: "#EC3748" }}>(</span><span style={{ color: "#EA3647" }}>(</span><span style={{ color: "#EA3647" }}>(</span><span style={{ color: "#EA3647" }}>(</span><span style={{ color: "#EA3647" }}>(</span><span style={{ color: "#EA3647" }}>(</span><span style={{ color: "#EA3647" }}>(</span><span style={{ color: "#EA3647" }}>(</span><span style={{ color: "#CE303F" }}>(</span><span style={{ color: "#A22531" }}>#</span><span style={{ color: "#840C10" }}>%</span><span style={{ color: "#840C10" }}>%</span><span style={{ color: "#840C10" }}>%</span><span style={{ color: "#940E10" }}>%</span><span style={{ color: "#AB1010" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BD1313" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#A31010" }}>%</span><span style={{ color: "#A31010" }}>%</span><span style={{ color: "#7F0C10" }}>%</span><span style={{ color: "#7F0C10" }}>%</span><span style={{ color: "#840C10" }}>%</span><span style={{ color: "#97222D" }}>#</span><span style={{ color: "#C52E3C" }}>#</span><span style={{ color: "#E83646" }}>(</span><span style={{ color: "#EA3647" }}>(</span><span style={{ color: "#EC3748" }}>(</span><span style={{ color: "#EA3647" }}>(</span><span style={{ color: "#EA3647" }}>(</span>
            </p>
            <p>
                <span style={{ color: "#EB3348" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93247" }}>(</span><span style={{ color: "#E93247" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93247" }}>(</span><span style={{ color: "#C62B3D" }}>#</span><span style={{ color: "#871D2A" }}>%</span><span style={{ color: "#880C10" }}>%</span><span style={{ color: "#880C10" }}>%</span><span style={{ color: "#B11111" }}>%</span><span style={{ color: "#A91111" }}>%</span><span style={{ color: "#9D0F11" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#A00F11" }}>%</span><span style={{ color: "#A00F11" }}>%</span><span style={{ color: "#A31010" }}>%</span><span style={{ color: "#A31010" }}>%</span><span style={{ color: "#B11111" }}>%</span><span style={{ color: "#7A1924" }}>%</span><span style={{ color: "#BA2839" }}>#</span><span style={{ color: "#E73247" }}>(</span><span style={{ color: "#E93247" }}>(</span><span style={{ color: "#EB3348" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93248" }}>(</span>
            </p>
            <p>
                <span style={{ color: "#EB3349" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#C82B3D" }}>#</span><span style={{ color: "#871D2A" }}>%</span><span style={{ color: "#900D11" }}>%</span><span style={{ color: "#900D11" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#B21212" }}>%</span><span style={{ color: "#A51012" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BD1313" }}>%</span><span style={{ color: "#980E0E" }}>%</span><span style={{ color: "#980E0E" }}>%</span><span style={{ color: "#980E0E" }}>%</span><span style={{ color: "#980E0E" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#A00F11" }}>%</span><span style={{ color: "#A21012" }}>%</span><span style={{ color: "#A31010" }}>%</span><span style={{ color: "#A31010" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#7A1925" }}>%</span><span style={{ color: "#B92839" }}>#</span><span style={{ color: "#E73247" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#EB3349" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93248" }}>(</span>
            </p>
            <p>
                <span style={{ color: "#EB3349" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#C62B3D" }}>#</span><span style={{ color: "#871D2A" }}>%</span><span style={{ color: "#900D11" }}>%</span><span style={{ color: "#900D11" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#B21212" }}>%</span><span style={{ color: "#A51012" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#980E0E" }}>%</span><span style={{ color: "#980E0E" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#A51012" }}>%</span><span style={{ color: "#A51012" }}>%</span><span style={{ color: "#980E0E" }}>%</span><span style={{ color: "#980E0E" }}>%</span><span style={{ color: "#BB1212" }}>%</span><span style={{ color: "#7A1925" }}>%</span><span style={{ color: "#B92839" }}>#</span><span style={{ color: "#E73247" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#EB3349" }}>(</span><span style={{ color: "#E93248" }}>(</span><span style={{ color: "#E93248" }}>(</span>
            </p>

        </code >
    );
};

export default LogoAsciArt;